baseURL: http://example.org/
languageCode: en-us
title: Erick
theme: "PaperMod"


params:
    homeInfoParams:
        Title: Memorias

    socialIcons:
        - name: "twitter"
          url: "https://www.twitter.com/ErickMMuniz_"
        - name: "instagram"
          url: "https://www.instagram.com/erickmmuniz"

